### ISSUE TITLE
Unable to retrieve the persisted state as a Record

### ISSUE THREAD

**Issue by antoinerey** [rt2zz/redux-persist-transform-immutable#10]
I set up a user Record like this :

``` js
const User = Immutable.Record({
  id: undefined,
  name: undefined,
}, 'User') // I specify the Record name
```

Then, I updated the transformers array like this :

``` js
const transforms = [
  immutableTransform({
    records: [ User ],
  }),
]

persistStore(store, { transforms }
```

My application state looks like this :

``` js
const state = {
  users: Immutable.Map({
    1: new User({
      id: 1,
      name: 'Harley Quinn'
    }),
    2: new User({
      id: 2,
      name: 'Nigma',
    }),
  }),
  ...
}
```

I'm using
- **redux** v3.5.2
- **redux-persist** v3.2.2
- **redux-persist-transform-immutable** v3.1.0
- **immutable** v3.8.1

Every time I refresh, the state is rehydrated as an Immutable.Map and not as User Records. Is there something wrong ? 

**Edit**

After some research and investigations, it seems that I'm trying to use this library to do something it's not supposed to do. 😄  

Correct me if I'm wrong, but this library is aimed to transform the whole reducer and not every item in it ? And that's totally okay, my mistake.

**Comment by rt2zz** [comment]
@antoinerey correct. If you can figure out a clever way to apply nested records let me know I would love to support it!

**Comment by ThomasStubbe** [comment]
I'm also experiencing the same problem... is there any way to use the records-transformation on entities in Lists or Maps ?

**Comment by geroale** [comment]
Same issue here. The only way I found is to use a custom transform, but I don't really like this solution.
