### ISSUE TITLE
Peer dependency problem

### ISSUE THREAD

**Issue by michaelswe** [rt2zz/redux-persist-transform-immutable#16]
package.json states:

    "peerDependencies": {
      "redux-persist": ">=3.0.0"
    },

Having redux-perist@4.0.0-alpha6 installed doesn't seem to satisfy this dependency. If I change package.json to the following I get rid of the error:

    "redux-persist": ">=4.0.0-alpha6"

**Comment by rt2zz** [comment]
I just released 4.0 with the redux-persist set to * for the time being until things settle down 👍
