### ISSUE TITLE
EPEERINVALID

### ISSUE THREAD

**Issue by icynoangel** [rt2zz/redux-persist-transform-immutable#17]
When trying to install this package I get this error:

The package redux-persist@4.0.0-alpha6 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer redux-persist-transform-immutable@4.0.1 wants redux-persist@*

What is the solution for this issue?

**Comment by icynoangel** [comment]
Can you guys set it to require the exact latest version of redux-persist? Which is now 4.0.0-alpha6?

Or how else could I get this to work with npm 2?

**Comment by rt2zz** [comment]
done, just published 4.1.0 with the specified peer dep

**Comment by icynoangel** [comment]
Thank you!
