### ISSUE TITLE
Unmet Peer Dependency: redux-persist@4.1.0

### ISSUE THREAD

**Issue by PizzaBrandon** [rt2zz/redux-persist-transform-immutable#19]
```
"peerDependencies": {
  "redux-persist": "~4.0.0"
},
```

With `redux-persist` moving to 4.1.0, the above dependency selector is unmet. (`~4.0.0` allows up to, but not including 4.1.0). Can this either be moved to `^4.0.0` or `~4` (equivalent syntax)? Thanks!

**Comment by rt2zz** [comment]
good catch `^4.0.0` it is. ty

**Comment by PizzaBrandon** [comment]
Can you please publish the updated version, too? 😄  Thanks!

**Comment by rt2zz** [comment]
published 4.2.0

**Comment by PizzaBrandon** [comment]
Many thanks!
