### ISSUE TITLE
Don't use transit-js

### ISSUE THREAD

**Issue by ntucker** [rt2zz/redux-persist-transform-immutable#23]
120kb is a lot to add just to serialize immutable structures. I'm sure there's another way to do this

**Comment by rt2zz** [comment]
I am aware of no alternative but open to suggestion

**Comment by chrisgbaker** [comment]
Following, as this dependency of a dependency (currently directly using redux-persist-immutable, not redux-persist-transform-immutable) is the second largest part of my entire bundle, and about ~25% of said bundle.

**Comment by rt2zz** [comment]
if someone cares to play around with it, this is probably be a good (and perhaps drop-in) alternative: https://github.com/zalmoxisus/remotedev-serialize

**Comment by inakianduaga** [comment]
@rt2zz thanks for the suggestion above, I agree with @ntucker that 120kb minified is crazy big for an arguably small feature of an app.

Bundle sizes for reference 

[remotedev-serialize](https://bundlephobia.com/result?p=remotedev-serialize@0.1.0)
[this project](https://bundlephobia.com/result?p=redux-persist-transform-immutable@4.3.0)

**Comment by ntucker** [comment]
I tried it out and it even works with immutable 4! https://github.com/rt2zz/redux-persist-transform-immutable/pull/25

**Comment by chrisgbaker** [comment]
Is there anything holding back a major version release with the changes in #25 ?

**Comment by rt2zz** [comment]
so I think the way to do this is to release it as a major version and put a big migrate at your own risk note on it. Basically any old persisted state will be lost.

**Comment by rt2zz** [comment]
just published v5!

**Comment by ntucker** [comment]
Will a new https://github.com/rt2zz/redux-persist-immutable also be published? No way to force it to use this version since it's a major bump

**Comment by rt2zz** [comment]
I suppose we could do a redux-persist-immutable v5 which bumps the dep here. It may be confusing since redux-persist-immutable will still depend on redux-persist@4, but that should all be handled on the hood and not a concern for most users.

**Comment by chrisgbaker** [comment]
Any more thought on bumping the version of `redux-persist-immutable`? as @ntucker said, it's not possible to use v5 of `redux-persist-transform-immutable` yet.
