### ISSUE TITLE
New version 3.x to npm

### ISSUE THREAD

**Issue by emroot** [rt2zz/redux-persist-transform-immutable#6]
hey @rt2zz, mind publishing this version to npm?

Thanks.

**Comment by emroot** [comment]
oh wait, it's been renamed. that's why npm couldn't find the new version. lemme try with the new name

**Comment by rt2zz** [comment]
Ya, i probably should have put better notes in the readme. If you install the newly renamed redux-persist - tranform-immutable you will need redux-persist v3 as well

**Comment by emroot** [comment]
cool cool. thanks!

**Comment by emroot** [comment]
worked like a charm
