### ISSUE TITLE
Issue with config

### ISSUE THREAD

**Issue by jeroenbourgois** [rt2zz/redux-persist-transform-immutable#9]
The check for config is not enough, this gives an error:

`if(config.records` because when config is undefined it will try to read records. I propose

`if(config && config.records)` ?

If you want I will make a PR

**Comment by jeroenbourgois** [comment]
For now I can bypass it by sending a nullified config with the function: `{records: null}`

**Comment by jdmunro** [comment]
I also have the same issue. Thanks for the workaround!

**Comment by antoinerey** [comment]
You can just give an empty configuration object.

```js
persistStore(store, {
  transforms: [ immutableTransform({}) ],
})
```
